# Generated by Django 4.1.7 on 2023-04-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.FloatField()),
                ('expiry_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDelivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpaApp.productdelivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpaApp.product')),
            ],
            options={
                'unique_together': {('product', 'delivery')},
            },
        ),
    ]
