# Generated by Django 4.1.7 on 2023-05-12 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.FloatField()),
                ('expiry_duration', models.DurationField()),
                ('deficit_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDelivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('service_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('RECEPTIONIST', 'Receptionist'), ('ACCOUNTANT', 'Accountant'), ('SUPPLIER', 'Supplier'), ('COSMETHOLOGIST', 'Cosmethologist')], default='OWNER', max_length=50, verbose_name='Role')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaApp.client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpaApp.productdelivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpaApp.product')),
            ],
            options={
                'unique_together': {('product', 'delivery')},
            },
        ),
    ]
