# Generated by Django 4.1.7 on 2023-04-09 14:42
from django.db import migrations


def insert_values(apps, schema_editor):
    product = apps.get_model('SpaApp', 'Product')
    # P7D stands for Period 7 Days
    product.objects.create(code='OIL000', name='Massage Oil', image=None, price=10., expiry_duration="P7D")
    product.objects.create(code='OIL001', name='Lavender Oil', image=None, price=15.5, expiry_duration="P7D")
    product.objects.create(code='SALT000', name='Bath Salts', image=None, price=5., expiry_duration="P14D")
    product.objects.create(code='MASK000', name='Clay Mask', image=None, price=10.5, expiry_duration="P14D")
    product.objects.create(code='MASK001', name='Green Tea Mask', image=None, price=20., expiry_duration="P14D")

    product_delivery = apps.get_model('SpaApp', 'ProductDelivery')
    product_delivery.objects.create(name='Massage Oil', amount=20, date='2023-04-09')
    product_delivery.objects.create(name='Lavender Oil', amount=10, date='2023-04-02')
    product_delivery.objects.create(name='Bath Salts', amount=15, date='2023-03-29')
    product_delivery.objects.create(name='Clay Mask', amount=5, date='2023-04-08')
    product_delivery.objects.create(name='Green Tea Mask', amount=10, date='2023-04-08')

    storage = apps.get_model('SpaApp', 'Storage')
    for product_, delivery in zip(product.objects.all(), product_delivery.objects.all()):
        storage.objects.create(product=product_,
                               delivery=delivery,
                               expiry_date=delivery.date + product_.expiry_duration)


class Migration(migrations.Migration):

    dependencies = [
        ('SpaApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_values)
    ]
