# Generated by Django 4.1.7 on 2023-04-09 15:33
import os
import shutil

from django.db import migrations
from django.core.files import File


def insert_values(apps, schema_editor):
    product = apps.get_model('SpaApp', 'Product')
    _add_image(product, 'Massage Oil', 'media/products/massage_oil.jpg')
    _add_image(product, 'Lavender Oil', 'media/products/lavender_oil.jpeg')
    _add_image(product, 'Bath Salts', 'media/products/bath_salts.jpg')
    _add_image(product, 'Clay Mask', 'media/products/clay_mask.jpeg')
    _add_image(product, 'Green Tea Mask', 'media/products/green_mask.jpeg')


def delete_values(apps, schema_editor):
    product = apps.get_model('SpaApp', 'Product')
    product.objects.all().delete()
    shutil.rmtree('media/images')


def _add_image(product_model, name, image_path):
    image_real_path = os.path.join('media', 'images', f'{name.replace(" ", "_")}.jpg')
    if os.path.exists(image_real_path):
        return

    product = product_model.objects.get(name=name)
    with open(image_path, 'rb') as f:
        product.image.save(f'{name}.jpg', File(f))


class Migration(migrations.Migration):

    dependencies = [
        ('SpaApp', '0002_seed_database'),
    ]

    operations = [
        migrations.RunPython(insert_values, reverse_code=delete_values)
    ]
