# Generated by Django 4.1.7 on 2023-04-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpaApp', '0004_user_accountant_owner_receptionist_supplier'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
