# Generated by Django 4.1.7 on 2023-04-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaApp', '0006_deficit'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='product',
    #         name='deficit_status',
    #         field=models.BooleanField(default=False),
    #     ),
    # ]
