# Generated by Django 4.1.7 on 2023-04-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpaApp', '0008_client_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deficit',
        ),
    ]
