# Generated by Django 4.1.7 on 2023-05-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpaApp', '0010_client_benefits_program_order'),
        ('SpaApp', '0011_service_upload'),
    ]

    operations = [
    ]
