# Generated by Django 4.1.7 on 2023-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaApp', '0013_cosmethologist_appointment_employee_appointment_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='benefits_program',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
