name: Build and push Docker image

on:
  pull_request:
    types: [ closed ]
  push:
    branches:
      - main
jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: 2115barti/spa_app
          addLatest: true
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}