name: Run Docker Compose and Django tests inside container

on:
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d
          
      - name: Run Django tests inside container
        run: |
          docker exec spamanagement_web_1 python manage.py test
