name: Run Docker Compose and List Containers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d
          
      - name: List Docker Containers
        run: |
          docker ps
