name: Static code analysis

on: [pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint-django django
    - name: Run Pylint
      run: pylint --load-plugins pylint_django --django-settings-module=SpaManagement.settings --fail-under=7.5 SpaApp/ SpaManagement/

